vim.cmd('set expandtab')
vim.cmd('set tabstop=2')
vim.cmd('set softtabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('set relativenumber')
vim.cmd('set clipboard^=unnamed,unnamedplus')
vim.cmd('set conceallevel=1')
vim.cmd('set cursorline')
vim.cmd('set mouse=')

